### PR TITLE
CircuitAI {1.2.8}

### PR DESCRIPTION
**Pull request by rlcevg**
Decreased wind's safe space in block_map.json, as otherwise it can't touch striderhub

### CODE REVIEW

**Comment by GoogleFrog** [comment]
Is it a problem if I have no way to delete files in deployed circuits?
image

**Comment by GoogleFrog** [comment]
What engine version does this go back to?

**Comment by GoogleFrog** [comment]
[infolog.txt](https://github.com/ZeroK-RTS/Chobby/files/11989581/infolog.txt)
I copied these four files into my deployed brutal and got this crash.
image

**Comment by GoogleFrog** [comment]
[infolog.txt](https://github.com/ZeroK-RTS/Chobby/files/11989709/infolog.txt)
I tried again and got an access violation on load.

**Comment by GoogleFrog** [comment]
I copied the files again and now it seems to work.

**Comment by GoogleFrog** [comment]
Thanks.

**Comment by rlcevg** [comment]
> Is it a problem if I have no way to delete files in deployed circuits? image

Shouldn't be an issue, those are few short text files. Circuit doesn't list contents of dirs and can't read files without direct links. All links to those files were cleared from AI.

**Pull request merged**
