### PR TITLE
Possibly fixed #2596

### PR DESCRIPTION
**Pull request by Cat-Lady**
Possible fixed:
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/2596

It seems that some builds of ZK interpret things following '//' (comment mark) as possible markers to resume interpreting,  while others not. I have no idea what causes the difference, but I've tested various .json interpreters, and indeed, some of the treat anything past '//' as comment to the end of the line, while others do not.

This commit aims to fix the issue at hand - hoever, in my opinion all our .json files should get scrutinized for comments formating and sanitized, OR reason for the difference in interpreting between ZK builds get discovered and ensured that all know what to do with comment lines.

### CODE REVIEW

**Comment by Anarchid** [comment]
Comments are not part of the JSON format, so if you want to make them valid, you should remove all comments.

CircuitAI as a project has a nonstandard JSON parser that allows comments. This is a CircuitAI bug.

**Comment by Cat-Lady** [comment]
Fixed missing coma that was causing the malformed config errors and "no defenses" bug in AI's below Hard, as per:
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/2596

**Comment by GoogleFrog** [comment]
I don't see why you remove comments from some of the files. You also need to bump configversions.

**Comment by Cat-Lady** [comment]
I'm not sure which of the comments are you referring to:

1. Some comments were moved (not deleted) to the position that stops confusing .json syntax parsers dujring editing. For example, comment at the end of line 28 makes syntax parsers that adhere to .json standards notice "weight:" in further lines as erroneous (while Shard interprets them all right).

Moving them was a compromise - comments were kept for documentation purposes, but stopped making edits (and spotting errors) harder. I said "compromise", cause non-compromise approach would be to either remove all comments (cause they're not part of .json standard), OR move it to -json variant that incorporates comments.

2. Some comments were removed, as they were no longer true - like, ones mentioning "fixme: sum of weight should = 1" were removed, cause I remade weights to sum up to full "1".

**Comment by GoogleFrog** [comment]
I am referring to the comments in all the other circuit files.

**Comment by Cat-Lady** [comment]
I just re-checked files changed:
https://github.com/ZeroK-RTS/Chobby/pull/699/files

...and I can't find removed comments. I see only moved comments, covered in point #1 in previous comment.

**Pull request closed without merging**
