### PR TITLE
upstream -> zk

### PR DESCRIPTION
**Pull request by gajop**

### CODE REVIEW

**Comment by GoogleFrog** [comment]
I dislike creating empty controls and moving the login screen elements around.

**Comment by gajop** [comment]
Sure, we could clean before the PR gets merged, @silentwings ?

**Comment by silentwings** [comment]
> I dislike creating empty controls

Ofc they could be removed with less clean code, handling two cases where necessary and several nil checks. Unless there is some practical damage caused by the empty controls, its not worth it.

> moving the login screen elements around

I'm bemused by this? Small adjustments to height/width occur to create necessary additional space but afaik nothing is "moved around".

**Comment by GoogleFrog** [comment]
@gajop I have no desire to merge multiple large and unused background images into the ZK build. Also, the merge now has conflicts.

**Comment by gajop** [comment]
Ok

**Pull request closed without merging**
