### PR TITLE
Make it german

### PR DESCRIPTION
**Pull request by DeinFreund**
How does it even detect what language to use though?

### CODE REVIEW

**Comment by gajop** [comment]
It doesn't do detection afaik, but users should be able to choose the language in the settings unless this option was removed.

If we want to do locale detection, it should be done in Spring so everyone could benefit.

**Comment by DeinFreund** [comment]
Hm, then this is pretty useless. Because 
 * People will not go as far as looking through the settings to find an obscure language option
 * The settings don't contain such an option as far as I can see

Engine changes are not planned. Can it be done within the menu somehow? I thought zk did system locale detection?

**Comment by GoogleFrog** [comment]
ZK does not do local detection. I don't think translation support is non-broken enough to consider enabling yet.

**Comment by Licho1** [comment]
I talked about INGAME where there is little german flag top right, that does nothing..
So units should be translated or flag nuked.
However I agree that lobby translations would be priority otherwise..

**Pull request merged**
